spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: practice

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core: DEBUG # 打印 mongodb 操作的具体语句。生产环境下，不建议开启。